"""add avatar and portrait fields

Revision ID: 9b89e5261019
Revises: 7a6cd32b9cf0
Create Date: 2026-05-11 11:43:05.721391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b89e5261019'
down_revision: Union[str, Sequence[str], None] = '7a6cd32b9cf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('portrait_photo_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('portrait_photo_url')
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###
