"""add goals table

Revision ID: a402e1ce0ee5
Revises: e580103acd01
Create Date: 2026-05-15 12:46:28.276604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'a402e1ce0ee5'
down_revision: Union[str, Sequence[str], None] = 'e580103acd01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('goal_type', sa.String(length=50), nullable=False),
    sa.Column('structured_data', sa.JSON(), nullable=True),
    sa.Column('embedding', Vector(dim=1536), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_index('idx_goals_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_goals_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index('idx_goals_user_type', ['user_id', 'goal_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_goals_goal_type'), ['goal_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_goals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_goals_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goals_user_id'))
        batch_op.drop_index(batch_op.f('ix_goals_status'))
        batch_op.drop_index(batch_op.f('ix_goals_goal_type'))
        batch_op.drop_index('idx_goals_user_type')
        batch_op.drop_index('idx_goals_user_status')
        batch_op.drop_index('idx_goals_created_at')

    op.drop_table('goals')
    # ### end Alembic commands ###
