"""add memories table with vector

Revision ID: e580103acd01
Revises: 9b89e5261019
Create Date: 2026-05-15 10:32:02.546011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'e580103acd01'
down_revision: Union[str, Sequence[str], None] = '9b89e5261019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('embedding', Vector(dim=1536), nullable=True),
    sa.Column('memory_type', sa.String(length=50), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.create_index('idx_memories_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_memories_user_type', ['user_id', 'memory_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memories_user_id'))
        batch_op.drop_index('idx_memories_user_type')
        batch_op.drop_index('idx_memories_created_at')

    op.drop_table('memories')
    # ### end Alembic commands ###
